<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Choose an optionNude</name>
   <tag></tag>
   <elementGuidId>b04a322f-b297-4d1d-83d5-9b640053aea4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pa_color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pa_color']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>995dc779-91a1-4fe5-87c4-ae21c50e4eff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_color</value>
      <webElementGuid>10df5fac-304f-4457-ab39-b68308d8a009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_color</value>
      <webElementGuid>dc7be0d5-a783-4118-8a5c-a8db3baf9919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_color</value>
      <webElementGuid>afc25901-2172-4436-9eba-bdc9617fe326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>5b7a46b3-3e6b-4c85-86c1-b965574a811e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an optionNude</value>
      <webElementGuid>c23ca2c5-f59c-425b-bc15-5cce5bda610c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_color&quot;)</value>
      <webElementGuid>f070957e-da91-4ab2-b308-9b2a189b9716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1a131f85-a747-4ea2-b39c-5519a9ddc1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pa_color</value>
      <webElementGuid>a95a1840-7c10-4228-9041-2108d676ff34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>attribute_pa_color</value>
      <webElementGuid>f6fcaa50-eeb5-40e4-b79c-a0c105aae136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-attribute_name</name>
      <type>Main</type>
      <value>attribute_pa_color</value>
      <webElementGuid>6b257534-a4c0-4d5b-adba-0371e5a86655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show_option_none</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>14bbe976-ad9a-4a42-b264-5980eed816ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose an optionNude</value>
      <webElementGuid>6a3c0263-70c1-4c26-9b12-4a272d8a81a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pa_color&quot;)</value>
      <webElementGuid>575b9408-d204-488b-8409-69fa6512b791</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pa_color']</value>
      <webElementGuid>764cc8e7-ae96-473b-a330-2970b872532a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-1418']/div/div[2]/form/table/tbody/tr/td/select</value>
      <webElementGuid>abe43764-da7e-4915-96ae-4023f48c7f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/following::select[1]</value>
      <webElementGuid>a47379fb-cf92-4394-9b76-31f349fd3eb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='product number'])[1]/following::select[1]</value>
      <webElementGuid>1c3303d3-9d19-4cc6-9cce-a1c1d0986574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/preceding::select[1]</value>
      <webElementGuid>0ac2b62b-7f8f-419c-b6dc-b58465d2d6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QTY'])[1]/preceding::select[2]</value>
      <webElementGuid>d1bba64c-0cc7-43f2-82d9-9757a50c0f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>15a1ba33-c7a6-44cb-a340-0f71fe02fbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'pa_color' and @name = 'attribute_pa_color' and (text() = 'Choose an optionNude' or . = 'Choose an optionNude')]</value>
      <webElementGuid>803b9b3a-3109-4e32-ace2-1e0cb66e1115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
