<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dismiss</name>
   <tag></tag>
   <elementGuidId>2a9ecd36-14ee-456c-848e-2ab342beccdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.woocommerce-store-notice__dismiss-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Dismiss')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7127aa91-0968-4449-825c-275258f2cef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>66b8ae1a-68fb-47fc-b9ac-fb8f3d44c1ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>f58cbfbc-da51-4ae5-a70a-e2d7cd652bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>2ec83c1c-70d2-4f24-81c3-f9511cc3eb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>6c5f4504-6e2f-4746-90f1-85fa995aa531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a86ee29-31e0-49fe-a9e1-886c3f4cdea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8aa24b8d-da7c-490a-9575-7097943a305a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>3835169c-b4e2-4495-b29c-9a4d53eb1903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>090f75b9-955b-4ef8-a2d1-acb5ccd029a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>1eaf4242-b0f4-411c-9146-b37c72a8eb41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>001af401-7c66-44b3-b614-2538b5986b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f8c86959-5867-47d5-af53-88871987734b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>c18f9aa4-ed47-465e-8731-f7ece93c30c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>f75be418-8ffc-447a-b3c3-d9d57da3cf55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>33b8d135-e75a-46ee-a476-3a5ef8b661ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>889983b9-6d5f-4646-9ccc-16603b28c04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6084790f-7740-4fd2-94bd-87883a45b2d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>abafcf6a-8beb-43da-b30b-b82114a61bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>32a54615-1759-42c2-a4b6-ac7c44629eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>d74f889b-c8ed-4f20-a35f-a931f806591d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11b3c028-db94-4d8c-8b84-f37dabcfcbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>766e956a-4d81-48d7-9cd9-e9dc45c621cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>b8c48c0c-1914-4b5a-9f90-c8bca0cb508a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>3369c177-61b4-4636-b65a-143d20fd3e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>0fe2d83b-d6c7-4f2b-b6fd-2923d5b8cfd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b5747e18-0a6a-48cc-80b4-97549d02289d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a901b4ff-8d47-413c-bca1-4351a6584710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>d2d3b017-f730-44d6-99a8-b9b65b046bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>ac00d624-d7df-4d8d-97dd-db407349c009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>6f3828da-ac86-4f50-8b76-1a12a85157c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>168c4927-a54c-4d8b-a03c-8a6381c5e1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>39c12e50-3ded-4de6-bcda-b4ec5c789860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>1764b9bf-d08f-47db-b618-7aa82975bfa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>f952e6bc-0b83-4ddd-89d0-dcc8b77a68cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>54995988-ef88-4618-89b3-22ce6610eb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9cb240c4-bc44-426d-9f27-d7ea7b66fc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4987c169-4f76-4050-84dd-46899e63fae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>ca6b7ad3-d387-4fe7-881a-038991b26740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>e03df7d2-1caf-4503-9daf-717f61cbe98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>c30397d0-327c-4417-9430-2e6d45fbee4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77bb6baa-14ba-484b-9aaf-791fe7399cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4dd4c9e5-0580-4ccf-abdf-faaf40b4c436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>125f4a59-1edf-43e1-8f44-20cedf4ab9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>4a6ce4cc-df8c-4157-a6f2-8cbcc1e9d3d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>8b479354-e6ea-457d-8752-be0414bfadd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>292340e8-3b3f-4ed6-95e9-d7b1fcf93c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d278add5-a6d0-4a50-8dd0-27e6f1a8b4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>65162950-1ade-4f63-92bb-03cb2aec6dad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>329c70a0-6f87-47ac-874f-9528497762ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>c6ac1b71-ca97-4cd9-93fb-57578f2ac28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>512d8c24-2c26-4062-b7bd-f9e69c698604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6a41d250-a040-4773-8c6b-2bf43683d096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>c225b7b1-1dea-41dd-9cef-faeb33828dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>bc489c45-0ec2-4814-813b-e8c7d6d8eb2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>2cce1fae-9db4-4ead-af26-d2a95a28377c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d78c41f2-1fb3-4f0b-b368-73ad6c1a28a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>e2f463bd-ec83-451f-a61b-48cf4bcf92da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>a1b42188-a5d0-4917-89a9-49092e825c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>50893056-c2bf-4750-a21b-4b8ab913c897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>8e1fa74d-adb0-4d86-82ba-0f76aa610257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>017e8899-9c6c-469d-926d-4ece24867829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6810f2f1-0cd4-46d7-92a6-f1b6eb92027e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>a699986b-db7b-4c89-ba66-7463b632d73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>d0abc007-6223-4322-8a42-4776d793f1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch js_active  vc_desktop  vc_transform  vc_transform&quot;]/body[@class=&quot;home page-template page-template-page-full-width page-template-page-full-width-php page page-id-522 wp-custom-logo theme-noo-mebla woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>d854a142-a9f7-46c7-a486-cdec6caa4527</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dismiss')]</value>
      <webElementGuid>6d12368d-6ae6-4563-be57-54ad029668cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We Work All The Holidays'])[1]/following::a[2]</value>
      <webElementGuid>a5b859be-22de-48fe-a1b3-53711a3967e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun: Closed'])[1]/following::a[2]</value>
      <webElementGuid>3a80942f-eb58-43c2-a5e5-d108f0bbebad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dismiss']/parent::*</value>
      <webElementGuid>23a464a2-811b-4bd2-ba1a-d4f0e6b20257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>e000ffdc-dd7c-44ca-bf99-4c9454fee98e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>6f7d202a-3edc-4b0e-93ba-a840167d3c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Dismiss' or . = 'Dismiss')]</value>
      <webElementGuid>40f62976-35fa-4f02-bfd2-d39e632653e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
