<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dismiss</name>
   <tag></tag>
   <elementGuidId>1fea0110-0597-4d41-b924-60fceeb7a8fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.woocommerce-store-notice__dismiss-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Dismiss')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed80154e-5de8-4bcf-b26f-f8b3d1c75d4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3f5c9448-29d1-4047-b4ad-3769ac93461d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-store-notice__dismiss-link</value>
      <webElementGuid>9a277b61-11bf-4b2b-af00-ff3152d4f667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dismiss</value>
      <webElementGuid>5ed459b8-e3ed-4f5b-b691-431921676987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;yes-js js_active js js no-touch&quot;]/body[@class=&quot;page-template-default page page-id-8 wp-custom-logo theme-noo-mebla woocommerce-account woocommerce-page woocommerce-demo-store woocommerce-js  page-fullwidth full-width-layout wpb-js-composer js-comp-ver-5.7 vc_responsive&quot;]/p[@class=&quot;woocommerce-store-notice demo_store&quot;]/a[@class=&quot;woocommerce-store-notice__dismiss-link&quot;]</value>
      <webElementGuid>db23b904-ab53-49c8-9482-a0d90fcb9697</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Dismiss')]</value>
      <webElementGuid>267553b5-4757-4409-82de-0e6655579d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We Work All The Holidays'])[1]/following::a[2]</value>
      <webElementGuid>9ba03556-cc77-46dd-add6-1211edc31ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sun: Closed'])[1]/following::a[2]</value>
      <webElementGuid>def5ede7-0215-449f-b7db-f4494b0b2b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dismiss']/parent::*</value>
      <webElementGuid>3eb2c68a-2037-4054-8df3-5e782ae9c3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>33a3baa9-9184-4cf6-996c-248d693654b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/p/a</value>
      <webElementGuid>09010e3f-fbfc-4bad-a131-2856126b6fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Dismiss' or . = 'Dismiss')]</value>
      <webElementGuid>16b26af4-6903-47ff-9a5e-45e556140bfd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
